{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "kafka:CreateCluster",
        "kafka:DescribeCluster",
        "kafka:DescribeClusterOperation",
        "kafka:UpdateCluster",
        "kafka:DeleteCluster",
        "kafka:ListClusters",
        "kafka:ListNodes",
        "kafka:ListClientV2",
        "kafka:ListTopics",
        "kafka:CreateConfiguration",
        "kafka:DescribeConfiguration",
        "kafka:ListConfigurations",
        "kafka:DeleteConfiguration",
        "kafka:PutClusterConfiguration",
        "kafka:BatchCreateTopics",
        "kafka:BatchDeleteTopics",
        "kafka:UpdateTopic",
        "ec2:DescribeVpcs",
        "ec2:DescribeSubnets",
        "ec2:DescribeSecurityGroups",
        "ec2:CreateSecurityGroup",
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:AuthorizeSecurityGroupEgress",
        "ec2:RevokeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupEgress",
        "ec2:DescribeNetworkInterfaces",
        "ec2:CreateNetworkInterface",
        "ec2:DeleteNetworkInterface",
        "cloudwatch:PutMetricData",
        "cloudwatch:GetMetricData",
        "cloudwatch:ListMetrics",
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "kms:DescribeKey",
        "kms:ListKeys",
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:GenerateDataKey",
        "iam:PassRole",
        "iam:GetRole",
        "iam:CreateRole",
        "iam:AttachRolePolicy",
        "iam:DetachRolePolicy"
      ],
      "Resource": "*"
    }
  ]
}
